print("Welcome to Git practical learning")
print("Login feature development started")
print("Main branch development started")
print("Profile feature development started")
print("Profile validation is being developed!")
