name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
env:
  APP_ENV: testing
  APP_NAME: git-learning-project

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
      
      - name: Show configuration
        run: |
          echo "Application: $APP_NAME"
          echo "Environment: $APP_ENV"
        
       - name: Show GitHub information
         run: |
           echo "Repository: $GITHUB_REPOSITORY"
           echo "Branch/ref: $GITHUB_REF"
           echo "Commit: $GITHUB_SHA"
           echo "Actor: $GITHUB_ACTOR"

  application:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run application
        run: python app.py
      
      - name: Show configuration
        run: |
          echo "Application: $APP_NAME"
          echo "Environment: $APP_ENV"