name: Reusable Python Test

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.12"

      environment:
        required: false
        type: string
        default: "testing"

    secrets:
      DEMO_SECRET:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show requested Python version
        run: |
          echo "Requested Python version: ${{ inputs.python-version }}"

      - name: Show environment
        run: |
          echo "Environment: ${{ inputs.environment }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest

      - name: Check reusable workflow secret
        env:
          DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
        run: |
          if [ -n "$DEMO_SECRET" ]; then
            echo "Secret successfully received by reusable workflow"
          else
            echo "Secret was not received"
            exit 1
          fi